// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDKSDatabase.Data;

#nullable disable

namespace RDKSDatabase.Migrations
{
    [DbContext(typeof(RDKSDatabaseContext))]
    [Migration("20220519220301_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RDKS.Models.HWY37N_HAZELTON", b =>
                {
                    b.Property<DateTime>("HWY_HAZ_DATE")
                        .HasColumnType("datetime2");

                    b.Property<float?>("HWY_HAZ_ABC_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_EST_OCC_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_FREON_REMOVAL_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_MARR_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_OCC_BIN_BILLING")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_SCRAP_METAL_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_TIRE_COLLECTION_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_TIRE_COUNTS")
                        .HasColumnType("real");

                    b.HasKey("HWY_HAZ_DATE");

                    b.ToTable("HWY37N_HAZELTON");
                });
#pragma warning restore 612, 618
        }
    }
}
