// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDKSDatabase.Data;

#nullable disable

namespace RDKSDatabase.Migrations
{
    [DbContext(typeof(RDKSDatabaseContext))]
    partial class RDKSDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RDKS.Models.HWY37N_HAZELTON", b =>
                {
                    b.Property<DateTime>("HWY_HAZ_DATE")
                        .HasColumnType("datetime2");

                    b.Property<float?>("HWY_HAZ_ABC_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_EST_OCC_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_FREON_REMOVAL_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_MARR_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_OCC_BIN_BILLING")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_SCRAP_METAL_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_TIRE_COLLECTION_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_HAZ_TIRE_COUNTS")
                        .HasColumnType("real");

                    b.HasKey("HWY_HAZ_DATE");

                    b.ToTable("HWY37N_HAZELTON");
                });

            modelBuilder.Entity("RDKS.Models.HWY37N_KITWANGA", b =>
                {
                    b.Property<DateTime>("HWY_KIT_DATE")
                        .HasColumnType("datetime2");

                    b.Property<float?>("HWY_KIT_CESA_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_CESA_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_EPRA_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_EPRA_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_FREON_REMOVAL_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_LAB_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_LAB_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_LIGHT_RECYCLE_COUNTS")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_LIGHT_RECYCLE_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_MARR_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_NET_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_OCC_HAULING_BIN_RENTAL")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_OCC_TONNAGE_EST")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_PAINT_RECYCLE_COUNTS")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_PAINT_RECYCLE_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_PPP_HAULING")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_PPP_TONNAGE")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_RECYCLE_BC_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_RECYCLE_BC_TONNAGE")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_SCRAP_METAL_MARR_INCLUDED")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_TIRE_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_TIRE_COUNTS")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_KIT_TOTAL_TONNES_EPR")
                        .HasColumnType("real");

                    b.HasKey("HWY_KIT_DATE");

                    b.ToTable("HWY37N_KITWANGA");
                });

            modelBuilder.Entity("RDKS.Models.HWY37N_STEWART", b =>
                {
                    b.Property<DateTime>("HWY_STE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<float?>("HWY_STE_BANDSTRA_OCC_HAULING")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_CESA_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_CESA_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_EPRA_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_EPRA_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_FREON_REMOVAL_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_LAB_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_LAB_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_LIGHT_RECYCLE_COUNTS")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_LIGHT_RECYCLE_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_MARR_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_NET_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_OCC_TONNES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_OCC_TOTAL")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_PAINT_RECYCLE_COUNTS")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_RECYCLE_BC_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_RECYCLE_BC_TONNAGE")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_RECYCLE_INCOME")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_SCRAP_METAL_MARR_TONNE_EST")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_TIRE_CHARGES")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_TIRE_COUNTS")
                        .HasColumnType("real");

                    b.Property<float?>("HWY_STE_TOTAL_TONNES_EPR")
                        .HasColumnType("real");

                    b.HasKey("HWY_STE_DATE");

                    b.ToTable("HWY37N_STEWART");
                });

            modelBuilder.Entity("RDKSDatabase.Models.ABCRecycling", b =>
                {
                    b.Property<DateTime?>("ABCDateID")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ABC_COMPLETED")
                        .HasColumnType("bit");

                    b.Property<string>("ABC_LOCATION")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ABC_MATERIAL")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<float?>("TOTAL_POUND_NETWEIGHT")
                        .IsRequired()
                        .HasColumnType("real")
                        .HasColumnName("ABC_NET_WEIGHT_IN_POUND");

                    b.Property<float?>("TOTAL_TONNAGE_MATERIAL")
                        .IsRequired()
                        .HasColumnType("real")
                        .HasColumnName("ABC_TOTAL_METRIC_TON");

                    b.Property<float?>("TOTAL_TONNAGE_NETWEIGHT")
                        .IsRequired()
                        .HasColumnType("real")
                        .HasColumnName("ABC_TOTAL_NET_WEIGHT_IN_TONNAGE");

                    b.HasKey("ABCDateID");

                    b.ToTable("ABCRecycling");
                });

            modelBuilder.Entity("RDKSDatabase.Models.Address", b =>
                {
                    b.Property<int>("ADDR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ADDR_ID"), 1L, 1);

                    b.Property<string>("ADDR_CITY")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ADDR_POCODE")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ADDR_PROV")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ADDR_STREET")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("CustomerCUS_ID")
                        .HasColumnType("int");

                    b.HasKey("ADDR_ID");

                    b.HasIndex("CustomerCUS_ID");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("RDKSDatabase.Models.Customer", b =>
                {
                    b.Property<int>("CUS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CUS_ID"), 1L, 1);

                    b.Property<int>("ADDR_ID")
                        .HasColumnType("int")
                        .HasColumnName("CUS_ADDRESS");

                    b.Property<int>("AddressesId")
                        .HasColumnType("int")
                        .HasColumnName("CUS_ALT_ADDRESS");

                    b.Property<string>("CUS_ACCNUM")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CUS_ALT_EMAIL")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CUS_ALT_PHONE")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CUS_COMPNAME")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CUS_DEACTIVATED_COUNT")
                        .HasColumnType("int");

                    b.Property<string>("CUS_EMAIL")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CUS_FNAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("CUS_FR")
                        .HasColumnType("bit");

                    b.Property<string>("CUS_LNAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("CUS_MEZ")
                        .HasColumnType("bit");

                    b.Property<string>("CUS_NOTE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CUS_PHONE")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("CUS_TTS")
                        .HasColumnType("bit");

                    b.HasKey("CUS_ID");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("RDKSDatabase.Models.Transaction", b =>
                {
                    b.Property<string>("TRANS_NUM")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CUS_ID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerCUS_ID")
                        .HasColumnType("int");

                    b.Property<string>("LICENSE_PLATE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TRANS_ADJUSTED_PRICE")
                        .HasColumnType("money");

                    b.Property<string>("TRANS_ANNUAL_REPORTING_GROUP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TRANS_ANNUAL_REPORTING_SOURCE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TRANS_ASC_NON_ASC")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime?>("TRANS_COMPLETION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TRANS_COMPLETION_TIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("TRANS_CONTRACT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<float?>("TRANS_CUBIC_METERS")
                        .HasColumnType("real");

                    b.Property<int?>("TRANS_CURBSIDE_AREA")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int?>("TRANS_CURBSIDE_STREAM")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<bool>("TRANS_DRIVER_EXEMPT_STATUS")
                        .HasColumnType("bit");

                    b.Property<string>("TRANS_FACILITY_CODE")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("TRANS_FUNCTION")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<bool>("TRANS_HASEXCEPTION")
                        .HasColumnType("bit");

                    b.Property<string>("TRANS_HAULER")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TRANS_IN_SERVICE_AREA")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<bool>("TRANS_ISMANUAL")
                        .HasColumnType("bit");

                    b.Property<int>("TRANS_LOAD_NUM")
                        .HasColumnType("int");

                    b.Property<float>("TRANS_NETWEIGHT")
                        .HasColumnType("real");

                    b.Property<int?>("TRANS_OPERATION")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int?>("TRANS_SERVICE_AREA")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int?>("TRANS_SOURCE_TYPE")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int?>("TRANS_STATUS")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<float>("TRANS_TONNES")
                        .HasColumnType("real");

                    b.Property<decimal>("TRANS_TOTALPRICE")
                        .HasColumnType("money");

                    b.Property<string>("VALID_IMPORT_CODE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ValidationVALID_IMPORT_CODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleLICENSE_PLATE")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TRANS_NUM");

                    b.HasIndex("CustomerCUS_ID");

                    b.HasIndex("ValidationVALID_IMPORT_CODE");

                    b.HasIndex("VehicleLICENSE_PLATE");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("RDKSDatabase.Models.Validation", b =>
                {
                    b.Property<string>("VALID_IMPORT_CODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VALID_AIRSPACE_OR_NONAIRSPACE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("VALID_CODE")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("VALID_CURBSIDE_STREAM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_CURBSIED_AREA")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_FACILITY")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_FR_ANNUAL_REPORTING_GROUP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_FR_ANNUAL_REPORT_WASTE_TYPE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_FUNCTION")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_IN_AND_OUT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_MATERIAL_GROUP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_MATERIAL_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VALID_SERVICE_AREA")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float?>("VALID_TIPPING_RATE")
                        .IsRequired()
                        .HasColumnType("real");

                    b.HasKey("VALID_IMPORT_CODE");

                    b.ToTable("Validation");
                });

            modelBuilder.Entity("RDKSDatabase.Models.Vehicle", b =>
                {
                    b.Property<string>("LICENSE_PLATE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("BADGE")
                        .HasColumnType("int");

                    b.Property<int>("CUS_ID")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTES_2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LICENSE_PLATE");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("RDKSDatabase.Models.Address", b =>
                {
                    b.HasOne("RDKSDatabase.Models.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerCUS_ID");
                });

            modelBuilder.Entity("RDKSDatabase.Models.Transaction", b =>
                {
                    b.HasOne("RDKSDatabase.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerCUS_ID");

                    b.HasOne("RDKSDatabase.Models.Validation", "Validation")
                        .WithMany()
                        .HasForeignKey("ValidationVALID_IMPORT_CODE");

                    b.HasOne("RDKSDatabase.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleLICENSE_PLATE");

                    b.Navigation("Customer");

                    b.Navigation("Validation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RDKSDatabase.Models.Customer", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
